// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwzBS1dGVEKZmo6L7hToOTOi1k1z26jEw',
    appId: '1:886398660689:web:d1a5254ba45a6920274870',
    messagingSenderId: '886398660689',
    projectId: 'currency-convertor-20a87',
    authDomain: 'currency-convertor-20a87.firebaseapp.com',
    storageBucket: 'currency-convertor-20a87.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK_mOkI7sbESwaLObCDgSl5Q21hoi6fZg',
    appId: '1:886398660689:android:38b9a23c558798eb274870',
    messagingSenderId: '886398660689',
    projectId: 'currency-convertor-20a87',
    storageBucket: 'currency-convertor-20a87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTurYjFJHBjoKeENKNpqgCtDxGi6M-NKo',
    appId: '1:886398660689:ios:03bc49c6fb1149c4274870',
    messagingSenderId: '886398660689',
    projectId: 'currency-convertor-20a87',
    storageBucket: 'currency-convertor-20a87.appspot.com',
    iosBundleId: 'com.example.convertor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTurYjFJHBjoKeENKNpqgCtDxGi6M-NKo',
    appId: '1:886398660689:ios:03bc49c6fb1149c4274870',
    messagingSenderId: '886398660689',
    projectId: 'currency-convertor-20a87',
    storageBucket: 'currency-convertor-20a87.appspot.com',
    iosBundleId: 'com.example.convertor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwzBS1dGVEKZmo6L7hToOTOi1k1z26jEw',
    appId: '1:886398660689:web:a0ca3870a6eb9aad274870',
    messagingSenderId: '886398660689',
    projectId: 'currency-convertor-20a87',
    authDomain: 'currency-convertor-20a87.firebaseapp.com',
    storageBucket: 'currency-convertor-20a87.appspot.com',
  );
}
